BATCH_SIZE: 2
max_epochs: -1 # -1 for no end

logging:
  root: 'training/ss_vctk'
  monitor: "Loss_G"
  save_every_n_epochs: 1 # -1 to just save the best and last
  save_samples: 0 # Positive to save examples of generated samples also
  scalars:
    - "Loss_G"
    - "Loss_D"
  samples:
    "x" : "audio"
    "G_x" : "audio"
  clear_cache_every_n_steps: 1
dataset:
  name: vctk
  val_split: 0.1
  kwargs:
    root: '/home/arsh/dev/data/VCTK/Dataset/'
    download: True

optimizers:
  gen:
    type: Adam
    kwargs:
      lr: 1.0e-4
      betas: 
        - 0.5
        - 0.9
  descrim:
    type: Adam
    kwargs:
      lr: 1.0e-4
      betas: 
        - 0.5
        - 0.9